### ISSUE TITLE
Cannot access to REST API

### ISSUE THREAD

**Issue by dinhdangkhoa** [atrocore/atropim#105]
Hi, 
I have installed AtroPIM on my server and I'm currently testing the API.
I checked the API documentation here : https://demo.atropim.com/apidocs/index.html

But, all my request has 404 Not found, I searched on google but I didn't find any resource to debug. You can see my request in the image.
Could you please provide more information, or maybe an example with Postman, to use REST API ?

Thank you
![image](https://user-images.githubusercontent.com/26383263/113880945-3db74980-97bc-11eb-9622-d64d69edd249.png)

**Comment by ozinch** [comment]
Hi, we have updated our guide for API usage: https://github.com/atrocore/atrocore-docs/blob/master/en/developer-guide/rest-api.md
Hope it helps.
