### ISSUE TITLE
Failed! Please, install mysqldump! System can't create dump for database!

### ISSUE THREAD

**Issue by rakibulinux** [atrocore/atropim#119]
Hello, @rratsun, How are you, friend?
I am getting this when I try to update my AtroPIM. Can you please take a look. My mysqldump is installed and working for backup DB. Also, my web interface is not working for updates. It's showing FAIL. Please guide me on how I can fix it?
Regards
Thanks

![Screenshot from 2021-04-26 19-57-11](https://user-images.githubusercontent.com/59226530/116095044-dd843b00-a6c9-11eb-8917-e874f668d202.png)
![image](https://user-images.githubusercontent.com/59226530/116095382-2a681180-a6ca-11eb-8408-ca2494e7202d.png)

**Comment by rratsun** [comment]
Hello, @rakibulinux
Try to execute ```mysqldump -h {$config['database']['host']} -u {$config['database']['user']} -p{$config['database']['password']} {$config['database']['dbname']}``` manually to define the problem. Use the same DB connection params as you use in atro config file (```/data/config.php```).

**Comment by rakibulinux** [comment]
Hello, @rratsun Thanks for the first reply.
Getting error like this.

You can see mysqldump is working but don't know what happens with `php composer.phar update`
`mysqldump --all-databases > mysqlbackup.sql`

![Screenshot from 2021-04-29 15-54-16](https://user-images.githubusercontent.com/59226530/116533452-3559b680-a903-11eb-9a6d-367ba5aeebc3.png)

![Screenshot from 2021-04-29 15-57-25](https://user-images.githubusercontent.com/59226530/116533949-c761bf00-a903-11eb-9eea-525d3b1286ae.png)

**Comment by rakibulinux** [comment]
Now getting another error: 
Error: Unsuccessful attempt to download translations

![Screenshot from 2021-04-29 16-08-30](https://user-images.githubusercontent.com/59226530/116535114-325fc580-a905-11eb-85d3-546dd4ccc741.png)

**Comment by rratsun** [comment]
You didn't understand me.
You should execute:
```mysqldump -h {$config['database']['host']} -u {$config['database']['user']} -p{$config['database']['password']} {$config['database']['dbname']}```

but firstly replace variables by yours DB configuration.

after replacing you should have something like this:
```mysqldump -h localhost -u root -pqwerty123 atrocore```

**Comment by rratsun** [comment]
As for another problem, try to read log filed. ```/data/logs/```

**Comment by Elvander** [comment]
I had both issues as well

The first issued has to do with the password encryption for mysql:
`mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect`

Multiple solutions are available [https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded](https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded)

As for the second issue this occurred when the content of config.php was completely erased. I have no idea  how it happend but during a cache refresh the contents of the config.php where removed. I restored it with a new config.php ( had to regenerated the passwords because of a different salt). But this resolved the issue.

**Comment by rakibulinux** [comment]
Hi, @rratsun, Getting an error like this.

Error: Unsuccessful attempt to download translations
![Screenshot from 2021-04-29 16-08-30](https://user-images.githubusercontent.com/59226530/116726061-94ebbb00-aa04-11eb-8778-3141c5fc21a4.png)


[2021-04-29 13:59:31] Log.ERROR: Uncaught Exception TypeError: "Argument 1 passed to Espo\Core\Utils\Language::__construct() must be of the type string, null given, called in /var/www/html/atrocores/vendor/atrocore/core/app/Treo/Services/Installer.php on line 665" at /var/www/html/atrocores/vendor/atrocore/core/app/Espo/Core/Utils/Language.php line 115 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Espo\\Core\\Utils\\Language::__construct() must be of the type string, null given, called in /var/www/html/atrocores/vendor/atrocore/core/app/Treo/Services/Installer.php on line 665 at /var/www/html/atrocores/vendor/atrocore/core/app/Espo/Core/Utils/Language.php:115)"} []

![Screenshot from 2021-04-30 22-36-11](https://user-images.githubusercontent.com/59226530/116726081-9d43f600-aa04-11eb-9342-fda04b3049b8.png)

**Comment by shoppersdirect** [comment]
@rratsun any help on this is greatly appreciated to get the pim up and running again

**Comment by rratsun** [comment]
Please, check your ```/data/config.php``` file. @Elvander wrote earlier that he has the similar problem and for some reason config.php was erased. We didn't reproduce this error yet, so we don't understand haw it can be. But we are working on it.

In the ```dump/``` directory you can find the last project dump, where you can find dump of config.php.

**Comment by rratsun** [comment]
> I had both issues as well
> 
> The first issued has to do with the password encryption for mysql:
> `mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect`
> 
> Multiple solutions are available https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded
> 
> As for the second issue this occurred when the content of config.php was completely erased. I have no idea how it happend but during a cache refresh the contents of the config.php where removed. I restored it with a new config.php ( had to regenerated the passwords because of a different salt). But this resolved the issue.

**Comment by rakibulinux** [comment]
> Please, check your `/data/config.php` file. @Elvander wrote earlier that he has the similar problem and for some reason config.php was erased. We didn't reproduce this error yet, so we don't understand haw it can be. But we are working on it.
> 
> In the `dump/` directory you can find the last project dump, where you can find dump of config.php.

Thanks @rratsun, It's fixed now
