### ISSUE TITLE
Unable to setup a parent under categories 

### ISSUE THREAD

**Issue by ebotas** [atrocore/atropim#132]
Trying to update an existing category the drop menu to select the parent don't shows anything and only to create a new category but even doing a new one it didn't assign to the existing category as a parent.

running the latest version 
core 1.2.38
pim 1.1.34
![Screen Shot 2021-06-01 at 13 59 22](https://user-images.githubusercontent.com/5151880/120391075-c699bf80-c2eb-11eb-9e8d-924590af9b44.png)
![Screen Shot 2021-06-01 at 13 59 31](https://user-images.githubusercontent.com/5151880/120391080-c7325600-c2eb-11eb-96a2-0b7078fc5a80.png)
![Screen Shot 2021-06-01 at 15 12 49](https://user-images.githubusercontent.com/5151880/120391138-d74a3580-c2eb-11eb-9d2c-7ad4ca73696f.png)

**Comment by rratsun** [comment]
Hello,

It's because you try to change root category. There is no ability to change parent for root category. The only thing that I see is no translates for validation. 

Translates will be added with next stable release (1.1.35) of PIM.
