### ISSUE TITLE
AWS S3 integration

### ISSUE THREAD

**Issue by hclaim** [atrocore/atropim#139]
Is there any way to integrate AWS S3 storage into this product? I haven't found anything in the documentation I have come across so far on how to do this. Kindly point me to the right documentation or configuration option on how to accomplish this.

**Comment by ozinch** [comment]
This feature is currently not planned. But if you wish to have it, we can implement it, if you finance 50% of costs. It will cost you 400 EUR. Please contact us via e-mail, if you are interested.
