### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by shoppersdirect** [atrocore/atropim#158]
I have ran dozens of imports to get them to work. If I add more than 10 fields, the configuration section clears and will no longer show any field matches. The fields continue to remove from the "unused fields" list. Also after I save I can no longer see the matched fields. What is going on here? Any help is greatly appreciated!

**Comment by ozinch** [comment]
Please make sure you are using the latest version of Import Feeds module. We are still actively working on this module. So an Update is available every week.
