### ISSUE TITLE
Product Gallery

### ISSUE THREAD

**Issue by shoppersdirect** [atrocore/atropim#204]
After the last update the Product Gallery View is just a blank white page.  The list view displays properly still.

**Comment by shoppersdirect** [comment]
@rratsun Is this being addressed?

**Comment by rratsun** [comment]
@shoppersdirect Can you show me log file with errors?

path to log file: YOUR_PROJECT_PATH/data/logs/atro-2022-04-01.log

**Comment by shoppersdirect** [comment]
@rratsun I will look at how to get those files. In the meantime your hosted demo is doing the same thing. 

List View Works: 
https://demo.atropim.com/#Product/list

Gallery View is Blank:
https://demo.atropim.com/#Product/plate

**Comment by rratsun** [comment]
I see. We will fix it in next release of PIM module.

**Comment by shoppersdirect** [comment]
@rratsun i just review this again and although it is working, the images are "fit/contain" to the boxes and therefors is only showing part of the image.
