### ISSUE TITLE
Multilanguage enum attribute value not initially stored in database after import

### ISSUE THREAD

**Issue by rmoecklideveloper** [atrocore/atropim#289]
I got attributes defined as enumeration and multi language, example color: When I do a csv import where the value is matched based on the main locale, I got after the import in the database table product_attribute_value: main: schwarz, fr_CH : null, it_CH : null. Only the matching value is present in the value table.

When I open the detail page of the product in pim gui, the value gets immediately written in the translated columns fr_Ch & it_CH.

Would be nice and expected, that after an import all language dependencies are written in the value table ;-)

**Comment by rratsun** [comment]
Fixed at Import Feeds 1.3.65.
