### ISSUE TITLE
Add Relation to many products causes 400 Error

### ISSUE THREAD

**Issue by rmoecklideveloper** [atrocore/atropim#337]
I made a combined product search, All products of family-Type A and have parent product B. Select all products the filter finds. Actions, add relation: choose Entity (my configured relation type, ist_zubehoer_von, which works on single products without issues), search desired related product, add relation -> Causes 400

System version: 1.4.128
Log: 

> [2022-11-28T10:28:49.262532+00:00] Log.ERROR: API [POST]:/api/v1/Product/associatedMainProducts/relation, Params:Array ( ) , InputData: {"ids":[],"foreignIds":["63583ebaeb3d0cb38"],"byWhere":true,"where":[{"type":"linkedWith","attribute":"parents","subQuery":[],"value":["63583ebaeb3d0cb38"]},{"type":"equals","attribute":"productFamilyId","subQuery":[],"value":"62fa5b42b01dbbe00"}],"associationId":"62e03b41a32aa82d0"} -  [] []
[2022-11-28T10:28:49.262770+00:00] Log.ERROR: Display Error: , Code: 400 URL: /api/v1/Product/associatedMainProducts/relation [] []

![gui_steps](https://user-images.githubusercontent.com/54440956/204255945-e395eb05-b19c-4f8c-9961-e1444ba9c776.png)
[atro-2022-11-28.log](https://github.com/atrocore/atropim/files/10102787/atro-2022-11-28.log)

**Comment by rratsun** [comment]
We have created an internal issue. We will inform you when the problem will solve.

**Comment by rratsun** [comment]
Fixed at PIM 1.5.99
