### ISSUE TITLE
Error: Not Found (404) during Atropim Installation Prozess

### ISSUE THREAD

**Issue by mabeuck** [atrocore/atropim#360]
during the last step in the installtionprozess i get this error:
![Winged9b1cfa8e-bc5a-4fcf-b09b-887d74e243f4Indianringneckparakeet](https://user-images.githubusercontent.com/96308456/210259731-d2d296ab-33c2-4b57-a982-8a249406d462.jpg)

When we install

git clone https://github.com/atrocore/skeleton-pim.git . && php composer.phar self-update && php composer.phar update

we get this message
![Lastingf3a92db4-de33-45d7-b2dd-705178c77401Tuna](https://user-images.githubusercontent.com/96308456/210260030-abdeac0d-eff6-4ed3-9b5e-c6bdceca944a.jpg)

**Comment by rratsun** [comment]
Hello,

The problem and the solution you can read [here](https://github.com/atrocore/atrocore/discussions/312).
