### ISSUE TITLE
Attribute value list «multi enum» import by csv/excel generates only one value_id

### ISSUE THREAD

**Issue by rmoecklideveloper** [atrocore/atropim#364]
Atropim v 1.6.1. / ImportFeed 1.4.18
attribute with text locale dependend, als multi value list configured. I got 130 Values in 3 languages. To import these into the system I used the importFeed. CSV with columns: attrcode, value_de, value_fr, value_it. Each Value is separated with ~ char.
Import works, the guy is displaying it correctly. When looking into the Database, it created just one value_id, which is wrong. Adding List items manually in gui creates for each item an id, which is referenced in the product_attribute_value table. 
further more, with an old import of the values to a product, also the text got imported in that table istead of Id's.

So in my case, I didn't see this at first and after an autom. update of the pim module I got suddenly [null][null]... values in the column: text_value

I fixed the data to my needs, created dummy id's and referenced the id's in the db, for now. 

<img width="1034" alt="atro_db_after_man_edit" src="https://user-images.githubusercontent.com/54440956/211556670-ecac3caf-c3b6-46bf-9b95-f328219d1597.png">
<img width="1011" alt="atro_db_after_import" src="https://user-images.githubusercontent.com/54440956/211556672-d4dcf800-1fc9-457e-bd77-3ddc178a2d4e.png">

![atro_import_feed_config](https://user-images.githubusercontent.com/54440956/211557215-bdfb5e3a-4a8d-4eef-8afc-beac550a1812.png)

![excel_extract](https://user-images.githubusercontent.com/54440956/211557296-7dc3035b-6b6c-4c3b-9ed8-8a3743310cdb.png)
[morach_vorteilstexte2023.xlsx](https://github.com/atrocore/atropim/files/10382917/morach_vorteilstexte2023.xlsx)

**Comment by rratsun** [comment]
Hello,
In last updates we have changed importing of list options. Now you can find Options Ids and Options Values fields for import. They are arrays. You can import them in "replace" mode or not. Option id it is the real value that will store to DB. Option Value is the label for option id.
