### ISSUE TITLE
Index of Enum Fields shifted after Update to 1.6.11

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atropim#365]
I've got these Enum fields

![image](https://user-images.githubusercontent.com/1337223/212134333-1dac726e-adc5-4f37-9e9f-58cc484dce7d.png)

After the update to 1.6.11 I noticed that the selected values are wrong. and shifted +1

in this case the "2" represents "nicht geeignet"
"nicht geeignet" should be "bedingt geeignet"
"bedingt geeignet" is supposed to be "geeignet"

![image](https://user-images.githubusercontent.com/1337223/212134129-7f56e99e-b99e-4926-a210-948738849356.png)

![image](https://user-images.githubusercontent.com/1337223/212156366-78b91ae0-cfe6-461d-b305-7a66b8d82a20.png)

Something happened around here:

https://github.com/atrocore/atropim/commit/9b8e886982079b81521cd22ebe248f00f01365eb
https://github.com/atrocore/atropim/commit/0ee483d5d6ecb4f7b34d6076e1ea0bfcab3d246c

I placed some debug Statements here: 

![image](https://user-images.githubusercontent.com/1337223/212152106-6a2c443b-a8f0-4dfd-8429-acb14a4755c3.png)

and this is the result:

```
[2023-01-12T18:40:53.079865+00:00] Log.DEBUG: attribute->typeValue ["geeignet","bedingt geeignet","nicht geeignet"] []
[2023-01-12T18:40:53.080815+00:00] Log.DEBUG: typeValueIds ["","0","1","2"] []
[2023-01-12T18:40:53.081047+00:00] Log.DEBUG: varcharValue 2 [] []
[2023-01-12T18:40:53.081225+00:00] Log.DEBUG: typeValue ["suitable","conditionally suitable","not suitable"] []
[2023-01-12T18:40:53.081384+00:00] Log.DEBUG: key 3 [] []
```

So I don't know why the data is how it is, but `typeValueIds` seems to throw things off. (I guess the `""` entry represents no selection in the enum drop down.

This whole check is not happening:

https://github.com/atrocore/atropim/blob/f0154a33f3bf063fd08c06c709260cb116b55153/app/Services/ProductAttributeValue.php#L824-L826

and therefore `$entity->get('value')` is not changing and stays 2.

I hope you can follow me. I don't know if that's a misconfiguration on my side or a side effect of recent changes.

Thanks for looking into it.

**Comment by rratsun** [comment]
One more bug fixed. Please update to PIM 1.6.12

**Comment by marcus-at-localhost** [comment]
Thank you so much for that prompt fix. Works as expected.
