### ISSUE TITLE
500 server error while mass deleting files

### ISSUE THREAD

**Issue by xpcovertech** [atrocore/atropim#373]
[https://youtu.be/aDNK26BfdgU](url)
Not able to mass delete products/any data from the Platform

**Comment by asapko** [comment]
Hello! We have tested this on our test platforms and could mass delete products. Could you give us more info (or may be in an issue of an older version)?

**Comment by xpcovertech** [comment]
Every few minutes, the DB connection is lost. I get 500 error.

**Comment by xpcovertech** [comment]
Now, the whole connection is lost and now I am reinstalling the app

**Comment by rratsun** [comment]
It looks like you have problem with your server. Try to change environment.
