### ISSUE TITLE
Error Creating New Attribute of Type List

### ISSUE THREAD

**Issue by paultvis** [atrocore/atropim#456]
Following the update to attributes and types, an error is raised. Error is 

Error 400: Validation failed. 'extensibleEnumId' is required.

Create a new attribute, update the code from the default generated code. Update any additional fields as required. Click save and create. Error is displayed

![atro_attribute_error](https://user-images.githubusercontent.com/31490804/235911025-f582f268-c256-4d90-a103-31d9f895840c.png)

**Comment by rratsun** [comment]
It is because you have customized layout and required field does not show.
Try to restore to default layout.
![image](https://user-images.githubusercontent.com/33658723/235939727-0dc9ccc6-f011-4519-ba73-f3733ed3af1e.png)
