### ISSUE TITLE
REST API Docs down?

### ISSUE THREAD

**Issue by MurmeltierS** [atrocore/atropim#54]
It seems like the REST API Docs are down:
https://demo.atropim.com/apidocs/index.html

**Comment by rratsun** [comment]
Hello
Thanks for information. We already fix the problem and now REST API Docs is working.

**Comment by SamuelHafner** [comment]
Why this doesnt work for me again?

**Comment by rratsun** [comment]
There was some problems with nginx. Now REST API Docs is working.
