### ISSUE TITLE
System is updating...

### ISSUE THREAD

**Issue by verstratenbram** [atrocore/atropim#605]
Our AtroCore installation is often stuck while updating.
![Screenshot at Jan 05 14-28-25](https://github.com/atrocore/atropim/assets/29309992/f701def6-224e-4482-8346-89ce7a92d083)
The only way to make the app available again is to delete `data/composer.log`.
Afterwards, updating manually via `php composer.phar update` works fine.

**Comment by AnnZast** [comment]
Hello
Please try to reboot the server.

**Comment by verstratenbram** [comment]
> Hello Please try to reboot the server.

Hi! There are multiple sites hosted on this server, so I want to avoid rebooting it. How would a server reboot fix composer issues?

**Comment by AnnZast** [comment]
Then you can simply restart the daemons on the server. Such a problem can occur if you have several PIM systems on the same server with the same id. PIM raises special daemons on the server bound to the system id. If there are several systems with the same id, then they work incorrectly.

If you want to get help in PIM installing and configuring, as well as receive timely answers to your questions, you can purchase one of our support packages. Here you can read what services it includes https://www.atropim.com/en/pricing

**Comment by verstratenbram** [comment]
I have added a worker to start the composer daemon `php index.php daemon composer <appID>` this seems to have solved the issue.
